/* Hermetic conf adapter so service_start re-creates services. */
[
    {
        type            : "adapter",
        adapterType     : "file",
        adapterId       : "conf",
        description     : "Conf objects for service start/stop",
        root            : "conf/",
        filenameSuffix  : ".json",
        contentType     : "json"
    },

    {
        type                : "requestHandler",
        uriPrefix           : "/",
        requestHandlerType  : "adapter"
    },

    {
        type            : "application",
        confAdapterId   : "conf",
        applicationId   : "ModelLifecycle"
    }
]
