FROM opensuse/leap:16.0

LABEL org.opencontainers.image.source=https://github.com/afw-org/afw

# Install packages
RUN zypper ref -s && \
    zypper -n in --force-resolution gcc gcc-c++ \
    libtool apache2-devel cmake clang-tools \
    libxml2 libxml2-devel \
    icu libicu-devel libunwind-devel \
    elfutils libdw1 libdw-devel libyaml-devel \
    FastCGI FastCGI-devel libmysqlclient-devel \
    libdb-4_8 libdb-4_8-devel libcurl-devel git \
    lmdb lmdb-devel libedit-devel doxygen rpm-build valgrind lato-fonts \
    openldap2-devel openldap2 libcurl4 \
    python3 python3-pip python3-devel \
    java-21-openjdk-headless nodejs22 npm22 && \
    zypper cc -a

RUN npm install -g npm-upgrade && npm install -g n && n 24
RUN npm install -g npm@10 eclint cspell

# install python packages
COPY python-requirements.txt /tmp/python-requirements.txt
RUN pip3 install --break-system-packages -r /tmp/python-requirements.txt

# install railroad ebnf syntax diagram generator
ADD https://github.com/afw-org/rr/releases/download/v1.63/rr.war /usr/local/bin/rr.war

CMD [ "bash" ]
