#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

version: '3'
services:
  afw:
    # Uncomment the next line to use a non-root user. On Linux, this will prevent
    # new files getting created as root, but you may need to update the USER_UID
    # and USER_GID in .devcontainer/Dockerfile to match your user if not 1000.
    # user: vscode

    build: 
      context: .
      dockerfile: Dockerfile

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ../..:/workspaces:cached
      # using a volume for the entire workspace will make building faster on Mac/Windows due to I/O.
      - afw-workspace-vol:/workspace
      - afw-workspace-bashhistory:/commandhistory
      - afw-workspace-extensions:/root/.vscode-server/extensions
      - afw-workspace-extensions-insiders:/root/.vscode-server-insiders/extensions

      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker.sock       

      # persistent data storage for afwfcgi instance at /afw
      - data:/afw

    ports:
      - "8080:8080"            
      - "3000:3000"

    privileged: true

    # Uncomment the next four lines if you will use a ptrace-based debuggers like C++, Go, and Rust.
    cap_add:
     - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity 
    
volumes:
  data:
  afw-workspace-vol:
  afw-workspace-bashhistory:
  afw-workspace-extensions:
  afw-workspace-extensions-insiders:
