[
    {
        type            : "adapter",
        adapterType     : "file",
        adapterId       : "conf",
        root            : "conf/",
        filenameSuffix  : ".json",
        contentType     : "json"
    },
    {
        type                : "requestHandler",
        uriPrefix           : "/",
        requestHandlerType  : "adapter"
    },
    {
        type            : "application",
        confAdapterId   : "conf",
        applicationId   : "OvernightSoak"
    }
]
