[
    {
        type                : "requestHandler",
        uriPrefix           : "/",
        requestHandlerType  : "adapter"
    },
    {
        type                : "adapter",
        adapterType         : "file",
        adapterId           : "file",
        description         : "file adapter for multi-request orchestration sketch",
        root                : "objects/",
        filenameSuffix      : ".json",
        contentType         : "json"
    }
]
