ARG OS_VERSION=3.16.9
FROM alpine:${OS_VERSION}

LABEL org.opencontainers.image.source=https://github.com/afw-org/afw

RUN apk add --no-cache apr apr-util apr-util-ldap \
    apr-util-dbd_mysql apr-util-dbd_pgsql icu-libs fcgi \
    libxml2 libunwind elfutils curl db lmdb yaml libldap libedit nginx
