[
    {
        type                : "requestHandler",
        uriPrefix           : "/",
        requestHandlerType  : "adapter"
    },
    {
        type            : "adapter",
        adapterType     : "file",
        adapterId       : "journal",
        description     : "Event journal for inbox. Swap adapterType later.",
        root            : "journal/",
        filenameSuffix  : ".json",
        contentType     : "json"
    },
    {
        type            : "adapter",
        adapterType     : "file",
        adapterId       : "inbox",
        description     : "Producer writes here. Swap adapterType later.",
        root            : "inbox/",
        filenameSuffix  : ".json",
        contentType     : "json",
        journalAdapterId: "journal"
    },
    {
        type            : "adapter",
        adapterType     : "file",
        adapterId       : "outbox",
        description     : "Consumer writes here. Swap adapterType later.",
        root            : "outbox/",
        filenameSuffix  : ".json",
        contentType     : "json"
    }
]
